# Contex
device_memory_capacity: 2147483648.0
costmodel_gamma: 0.001
costmodel_beta: 280.0

# Dataset
data_url: "/home/data/dushens/dataset/mindspore/faces_emore_train"
num_classes: 85742

# Model
backbone: 'iresnet50' # 'mobilefacenet', 'iresnet50', 'iresnet100'
method: "arcface"
num_features: 512

# Train parameters
epochs: 25
batch_size: 256
learning_rate: 0.02
schedule: [10, 16, 21]
gamma: 0.1
momentum: 0.9
weight_decay: 0.0001

# Checkpoint
save_checkpoint_steps: 60
keep_checkpoint_max: 20
train_url: '.'
resume: False
