# Train parameters setting
epochs: 25
num_classes: 10572
batch_size: 256
learning_rate: 0.02
schedule: [10, 16, 21]
gamma: 0.02
momentum: 0.9
weight_decay: 0.0001
backbone: 'iresnet50' # 'mobilefacenet', 'iresnet50', 'iresnet100'
train_url: '.'

# Dataset
data_url: "/home/data/dushens/dataset/mindspore/faces_webface_112x112_train"
